language: python
dist: bionic

matrix:
  include:
    # The pypy tests are slow, so we list them first
    - python: pypy3.6-7.2.0
    - language: generic
      env: PYPY_NIGHTLY_BRANCH=py3.6
    - python: 3.6-dev
    - python: 3.7-dev
    - python: 3.8-dev
    # Disabling nightly until greenlet makes a release that includes
    # https://github.com/python-greenlet/greenlet/pull/161
    #- python: nightly

script:
  - ./ci.sh

branches:
  except:
    - /^dependabot/.*/
